name: Review dependencies

on:
  - push
  - workflow_dispatch
  
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency Review
        uses: actions/dependency-review-action@v3.0.4
